apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-sample.fullname" . }}-html
  labels:
    {{- include "helm-sample.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hola Mundo</title>
        <meta charset="UTF-8">
        <style>
            body {
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                font-family: Arial, sans-serif;
                background-color: #f0f0f0;
            }
            h1 {
                font-size: 3em;
                color: #333;
            }
        </style>
    </head>
    <body>
        <h1>hola mundo</h1>
    </body>
    </html>
